### ISSUE TITLE
Add persistent bot stats

### ISSUE THREAD

**Issue by misaugstad** [payros/super-gomoku#3]
Keeping a database of stats for wins/losses for every bot against every other bot (and against humans) would be useful for human players to have when deciding which bot to play against. These stats will give them an indication of which bots are harder to beat.

It may also encourage the makers of bots to improve their bots, in an effort to reach the top of the rankings :)

Could also be useful in future iterations of this class, for viewing tournament stats :)

This will require adding a database to the back end, as well as some careful thought about how to display this information in an intuitive way, since we can't just show all head to head matchups at once. We'll have a discussion about this offline later this week.

**Comment by misaugstad** [comment]
We decided to start with a simple implementation with just a single table; one row for each bot, with something like 5 columns (bot name, wins vs humans, losses vs humans, wins vs bots, losses vs bots). Once that basic implementation is working, we are considering recording the head-to-head wins/losses b/w the different bots (which would require a 2nd table)

**Comment by payros** [comment]
Implemented on [this commit](https://github.com/payros/super-gomoku/commit/08b260efccc98d1020623b24af2fddfbc8f36c80)
