### ISSUE TITLE
Have a bot set up to play against as default

### ISSUE THREAD

**Issue by misaugstad** [payros/super-gomoku#5]
It is not immediately clear how one would get to play against one of the bots, so it would at least be good to have one set up as default.

Suggested by @nikivazou

**Comment by misaugstad** [comment]
Updated in [this commit](https://github.com/payros/super-gomoku/commit/1d2cd1449db0208ea06fc122d3afd62f346f4762).

**Comment by payros** [comment]
Actually, I'm not entirely sure this is a good idea. While adding a bot as the default will show the user they can play against bots it will hide the human X human functionality. I think the fact that the bots exist on a column to the right is enough to guide the user.

**Comment by payros** [comment]
Also, setting any one bot as the default will likely skew the statistics in favor of that bot. Much better to remain neutral.

**Comment by misaugstad** [comment]
>Actually, I'm not entirely sure this is a good idea. While adding a bot as the default will show the user they can play against bots it will hide the human X human functionality. I think the fact that the bots exist on a column to the right is enough to guide the user.

The thing is, 99% of the time, someone who uses the app is going to be alone, and will play against a bot. Having two users at the same machine to play a game doesn't seem like something that we should expect, so I don't think it should be the default. Although hiding the human v. human functionality is a good point, and we should think of a way to show that it is possible.

>Also, setting any one bot as the default will likely skew the statistics in favor of that bot. Much better to remain neutral.

Hopefully we can come up with a way to do the stats so that bots that are played more often are not seen more favorably than others.

**Comment by payros** [comment]
> The thing is, 99% of the time, someone who uses the app is going to be alone, and will play against a bot. 

Fair point. Well, I think I have a UI solution that may work for highlighting the human vs. human functionality.

As for the skewed statistics, perhaps we can randomize the "default bot". I think that would make things more interesting for the player as well.

**Comment by misaugstad** [comment]
>perhaps we can randomize the "default bot". I think that would make things more interesting for the player as well.

Agreed. :)

**Comment by payros** [comment]
Officially closed with [this commit](https://github.com/payros/super-gomoku/commit/885ae7ecf3b2957a299e859270394e6480d4a7d9).

**Comment by payros** [comment]
Officially closed with [this commit](https://github.com/payros/super-gomoku/commit/885ae7ecf3b2957a299e859270394e6480d4a7d9).
