### ISSUE TITLE
Possibly allow clicking on bot name to play against them

### ISSUE THREAD

**Issue by misaugstad** [payros/super-gomoku#6]
Right now we just have a click and drag, which is not necessarily intuitive. One alternative would be that when a user clicks on a bot name, a popup asks them which player slot the bot should play in.

**Comment by payros** [comment]
There is also an autocomplete feature. When you start typing the player’s name, you get bot suggestions. But I’ll probably add some visual queue that the bots are draggable for the user

**Comment by payros** [comment]
Implemented on [this commit](https://github.com/payros/super-gomoku/commit/f8ac61462a4c264b04f38c02600f93b42dfff777)
